try to publish tests results

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -29,5 +29,18 @@ jobs:
     - name: Test
       if: ${{ matrix.os == 'ubuntu-latest' }}
       working-directory: ${{github.workspace}}/build
-      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target check -j $(nproc)
-      
+      run: |
+        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target check -j $(nproc)
+        mkdir ${{github.workspace}}/tests-results
+        cp $(find ${{github.workspace}}/build -name *.xml) ${{github.workspace}}/tests-results
+
+    - name: Print test log on failure
+      if: ${{ matrix.os == 'ubuntu-latest' }} && failure()
+      run: |
+        cat ${{github.workspace}}/build/Testing/Temporary/LastTest.log
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v6
+      if: ${{ matrix.os == 'ubuntu-latest' }} && (success() || failure()) # always run even if the previous step fails
+      with:
+        report_paths: '**/tests-results/*.xml'
